AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 120
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: Api
        SECRET_NAME: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}
        DATABASE_ENDPOINT: !Ref DatabaseEndpoint

Parameters:
  SecurityGroupId:
    Description: Security Group for the application
    Type: String
    Default: "sg-08261dbff27934074"
  Subnet1Id:
    Description: Subnet Id for the first subnet
    Type: String
    Default: "subnet-0c381055bcc5c5afa"
  Subnet2Id:
    Description: Subnet Id for the second subnet
    Type: String
    Default: "subnet-008eab0d04534c97c"
  DatabaseSecretName:
    Description: The name of the secret holding database credentials
    Type: String
    Default: "titancbaccount"
  DatabaseEndpoint:
    Description: The endpoint of the database
    Type: String
    Default: "titan-database.cltwdcyzib6f.ap-southeast-1.rds.amazonaws.com"


Resources:
  ApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .\target\App.jar
      Handler: com.example.payment.config.StreamLambdaHandler::handleRequest
      Runtime: java17
      AutoPublishAlias: production
      SnapStart:
        ApplyOn: PublishedVersions
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupId
        SubnetIds:
          - !Ref Subnet1Id
          - !Ref Subnet2Id
      Architectures:
        - x86_64
      MemorySize: 2048
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${DatabaseSecretName}
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY
  SwaggerUiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: The Lambda function that serves the Swagger UI.
      CodeUri: .\target\App.jar
      Handler: com.example.payment.config.StreamLambdaHandler::handleRequest
      Runtime: java17
      AutoPublishAlias: production
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        SwaggerUiApi:
          Type: Api
          Properties:
            Path: /swagger-ui
            Method: GET
        SwaggerUiApiProxy:
          Type: Api
          Properties:
            Path: /swagger-ui/{proxy+}
            Method: GET